events {}

http {
  upstream candidate { server candidate-portal:3000; }
  upstream company   { server company-portal:3001; }
  upstream admin     { server admin:3002; }
  upstream api       { server backend:4000; }
  upstream ai        { server ai-fastapi:8000; }

  server {
    listen 80;

    location /candidate/ { proxy_pass http://candidate/; }
    location /company/   { proxy_pass http://company/; }
    location /admin/     { proxy_pass http://admin/; }
    location /api/       { proxy_pass http://api/api/; }
    location /ai/        { proxy_pass http://ai/; }
  }
}
